# Generated by Django 3.1.1 on 2020-11-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201108_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
