# Generated by Django 3.1.1 on 2020-11-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='health_issues',
            field=models.CharField(choices=[('Assthama', 'Assthama'), ('Diabetes', 'Diabetes'), ('BP Fluctuation', 'BP Fluctuation'), ('Heart Problem', 'Heart Problem'), ('Back Problem', 'Back Problem'), ('Slip Disc', 'Slip Disc')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
