# Generated by Django 3.1.1 on 2020-11-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201108_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], default='A+', max_length=10),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='health_issues',
            field=models.CharField(choices=[('None', 'None'), ('Assthama', 'Assthama'), ('Diabetes', 'Diabetes'), ('BP Fluctuation', 'BP Fluctuation'), ('Heart Problem', 'Heart Problem'), ('Back Problem', 'Back Problem'), ('Slip Disc', 'Slip Disc')], default='None', max_length=30),
        ),
    ]
