# Generated by Django 3.1.1 on 2020-11-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_newuser_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='health_issues',
        ),
    ]
